[package]
name = "verify-signature"
version = "0.1.0"
authors = ["David Keeler <mozkeeler@gmail.com>"]
description = "verify a signature"
license = "MPL-2.0"
categories = ["cryptography"]
keywords = ["signature", "verification"]

[dependencies]
scopeguard = "0.3.2"
